"""Add multi-tenancy support

Revision ID: 0a20250a2e4e
Revises: 7984a53ed84c
Create Date: 2026-02-24 10:51:31.905757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a20250a2e4e'
down_revision: Union[str, Sequence[str], None] = '7984a53ed84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=True)
    op.add_column('events', sa.Column('college_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'colleges', ['college_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('college_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'colleges', ['college_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'college_id')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'college_id')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
