"""add_on_delete_cascade

Revision ID: c68fddb6c077
Revises: 0a20250a2e4e
Create Date: 2026-02-24 23:43:20.624882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68fddb6c077'
down_revision: Union[str, Sequence[str], None] = '0a20250a2e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_college_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_organizer_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('marketplace_items_owner_id_fkey'), 'marketplace_items', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace_items', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('participations_event_id_fkey'), 'participations', type_='foreignkey')
    op.drop_constraint(op.f('participations_user_id_fkey'), 'participations', type_='foreignkey')
    op.create_foreign_key(None, 'participations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('travel_plans_organizer_id_fkey'), 'travel_plans', type_='foreignkey')
    op.create_foreign_key(None, 'travel_plans', 'users', ['organizer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_college_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('verification_requests_user_id_fkey'), 'verification_requests', type_='foreignkey')
    op.create_foreign_key(None, 'verification_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_requests', type_='foreignkey')
    op.create_foreign_key(op.f('verification_requests_user_id_fkey'), 'verification_requests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_college_id_fkey'), 'users', 'colleges', ['college_id'], ['id'])
    op.drop_constraint(None, 'travel_plans', type_='foreignkey')
    op.create_foreign_key(op.f('travel_plans_organizer_id_fkey'), 'travel_plans', 'users', ['organizer_id'], ['id'])
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.create_foreign_key(op.f('participations_user_id_fkey'), 'participations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('participations_event_id_fkey'), 'participations', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'marketplace_items', type_='foreignkey')
    op.create_foreign_key(op.f('marketplace_items_owner_id_fkey'), 'marketplace_items', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_organizer_id_fkey'), 'events', 'users', ['organizer_id'], ['id'])
    op.create_foreign_key(op.f('events_college_id_fkey'), 'events', 'colleges', ['college_id'], ['id'])
    # ### end Alembic commands ###
