"""Add profile fields

Revision ID: ca93d4ca2774
Revises: 178f334b6c6a
Create Date: 2026-02-24 09:57:21.640775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca93d4ca2774'
down_revision: Union[str, Sequence[str], None] = '178f334b6c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(), nullable=True))
    op.add_column('users', sa.Column('college_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('theme_preference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_preference')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'college_name')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
